### PR TITLE
Fix flaky test in HybridQueryAggregationsIT

### LINKED ISSUE #1488: [Flaky Test] HybridQueryAggregationsIT testNestedAggs_whenMultipleShardsAndConcurrentSearchDisabled_thenSuccessful flaky for Multi-Node IT
Flaky error:
```
java.lang.AssertionError: expected:<42> but was:<84>
	at __randomizedtesting.SeedInfo.seed([E6CDBE73F2980B06:FA5B74F3F47A04AB]:0)
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.opensearch.neuralsearch.query.HybridQueryAggregationsIT.assertNestedAggregations(HybridQueryAggregationsIT.java:616)
	at org.opensearch.neuralsearch.query.HybridQueryAggregationsIT.testNestedAggs_whenMultipleShardsAndConcurrentSearchDisabled_thenSuccessful(HybridQueryAggregationsIT.java:469)
```

### PR DESCRIPTION
**Pull request by chishui**
### Description
The test fails because when preparing documents using `bulkIngest` function, we may get `primary shard is not active` issue. The fix adds a `waitForClusterHealthGreen` check before running `bulkIngest`. Also update `waitForClusterHealthGreen` to wait for active shard as well.

Verified through:
```
./gradlew integTest -PnumNodes=3  -Dtests.iters=10 --tests "org.opensearch.neuralsearch.query.HybridQueryAggregationsIT.testNestedAggs_whenMultipleShardsAndConcurrentSearchDisabled_thenSuccessful"
```

### Related Issues
Resolves #1488 #1489 

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/neural-search/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java [hunk 1]
```diff
@@ -2025,11 +2026,18 @@ protected String registerModelGroup(final String modelGroupRegisterRequestBody)
...
+        waitForClusterHealthGreen(numOfNodes, timeoutInSeconds, "0");
+    }
+
+    // Method that waits till the health of nodes in the cluster goes green
+    protected void waitForClusterHealthGreen(final String numOfNodes, final int timeoutInSeconds, final String activeShards)
+        throws IOException {
         Request waitForGreen = new Request("GET", "/_cluster/health");
         waitForGreen.addParameter("wait_for_nodes", numOfNodes);
         waitForGreen.addParameter("wait_for_status", "green");
+        waitForGreen.addParameter("wait_for_active_shards", activeShards);
```
Comment (heemin32) [inline src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java]: Can we just use "all"

```suggestion
        waitForGreen.addParameter("wait_for_active_shards", "all");
```

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java [hunk 2]
```diff
@@ -151,13 +151,14 @@ public abstract class BaseNeuralSearchIT extends OpenSearchSecureRestTestCase {
...
     private static final long TIMEOUT = 10000;
+    protected String numOfNode;
 
     @Before
     public void setupSettings() {
         threadPool = setUpThreadPool();
         clusterService = createClusterService(threadPool);
         final IndexNameExpressionResolver indexNameExpressionResolver = new IndexNameExpressionResolver(new ThreadContext(Settings.EMPTY));
-
+        numOfNode = System.getProperty("cluster.number_of_nodes", "1");
```
Comment (heemin32) [inline src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java]: Why do we set the number of node as 1 here?

Comment (chishui) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java]: oh, it's the default value if numNodes is not set

Comment (chishui) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:161]: in multi-node testing from workflow or locally, this could be any number

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java (hunk 1 above)
Comment (chishui) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java]: It's "0" by default for health API, don't want to change the behavior for all other unrelated usage. WDYT?

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java (hunk 2 above)
Comment (heemin32) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java]: Why do we need to set it explicitly if it is already a default value?

File: src/test/java/org/opensearch/neuralsearch/query/HybridQueryAggregationsIT.java [hunk 3]
```diff
@@ -496,6 +496,8 @@ private void prepareResourcesForNestegAggregationsScenario(String index) throws
             String ingestBulkPayload = Files.readString(Path.of(classLoader.getResource("processor/ingest_bulk.json").toURI()))
                 .replace("\"{indexname}\"", "\"" + index + "\"");
 
+            // wait until cluster is healthy before running ingest to reduce flakiness
+            waitForClusterHealthGreen(numOfNode, 60, "all");
```
Comment (heemin32) [inline src/test/java/org/opensearch/neuralsearch/query/HybridQueryAggregationsIT.java]: Why this test is special that it have to pass "all" while others test does not pass the same value?

Comment (chishui) [reply src/test/java/org/opensearch/neuralsearch/query/HybridQueryAggregationsIT.java]: Your point makes sense, I'll change "all" as default

**Comment by chishui** [comment]
cluster status could be yellow as replica shard can't be assigned to the same node as primary shard when we run single node test:
```
  1> [2025-08-15T09:41:46,101][INFO ][o.o.n.BaseNeuralSearchIT ] [testNestedAggs_whenMultipleShardsAndConcurrentSearchDisabled_thenSuccessful] retry: 2
  1> [2025-08-15T09:42:26,120][INFO ][o.o.n.q.HybridQueryAggregationsIT] [testNestedAggs_whenMultipleShardsAndConcurrentSearchDisabled_thenSuccessful] {"index":"test-hybrid-
nested-aggs-multi-doc-index","shard":0,"primary":false,"current_state":"unassigned","unassigned_info":{"reason":"INDEX_CREATED","at":"2025-08-15T07:40:35.279Z","last_allocat
ion_status":"no_attempt"},"can_allocate":"no","allocate_explanation":"cannot allocate because allocation is not permitted to any of the nodes","node_allocation_decisions":[{
"node_id":"NYlCvB51Qx6oT7ZNJRrncw","node_name":"integTest-0","transport_address":"127.0.0.1:49498","node_attributes":{"testattr":"test","shard_indexing_pressure_enabled":"tr
ue"},"node_decision":"no","weight_ranking":1,"deciders":[{"decider":"same_shard","decision":"NO","explanation":"a copy of this shard is already allocated to this node [[test
-hybrid-nested-aggs-multi-doc-index][0], node[NYlCvB51Qx6oT7ZNJRrncw], [P], s[STARTED], a[id=6HuvC2OPTV6EbpPrX2W_ag]]"}]}]}
```

I add a logic to change num_of_replica to 0 if there is only one node.
