### PR TITLE
Fix minimal version of support analyzer in neural sparse

### LINKED ISSUE #1416: [Flaky test]rolling.NeuralSparseSearchIT.testSparseEncodingProcessor_E2EFlow
```
REPRODUCE WITH: ./gradlew ':qa:rolling-upgrade:testAgainstTwoThirdsUpgradedCluster' --tests "org.opensearch.neuralsearch.bwc.rolling.NeuralSparseSearchIT.testSparseEncodingProcessor_E2EFlow" -Dtests.seed=E42B39786EA922E1 -Dtests.security.manager=false -Dtests.bwc.version=3.0.0 -Dtests.locale=ff-Adlm-NE -Dtests.timezone=BET -Druntime.java=23


Suite: Test class org.opensearch.neuralsearch.bwc.rolling.NeuralSparseSearchIT
  2> REPRODUCE WITH: ./gradlew ':qa:rolling-upgrade:testAgainstTwoThirdsUpgradedCluster' --tests "org.opensearch.neuralsearch.bwc.rolling.NeuralSparseSearchIT.testSparseEncodingProcessor_E2EFlow" -Dtests.seed=E42B39786EA922E1 -Dtests.security.manager=false -Dtests.bwc.version=3.0.0 -Dtests.locale=ff-Adlm-NE -Dtests.timezone=BET -Druntime.java=23
  2> org.junit.ComparisonFailure: expected:<[0]> but was:<[1]>
        at __randomizedtesting.SeedInfo.seed([E42B39786EA922E1:2617D9E173359055]:0)
        at org.junit.Assert.assertEquals(Assert.java:117)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at org.opensearch.neuralsearch.bwc.rolling.NeuralSparseSearchIT.validateTestIndexOnUpgrade(NeuralSparseSearchIT.java:115)
        at org.opensearch.neuralsearch.bwc.rolling.NeuralSparseSearchIT.testSparseEncodingProcessor_E2EFlow(NeuralSparseSearchIT.java:77)
  2> NOTE: leaving temporary files on disk at: /home/runner/work/neural-search/neural-search/qa/rolling-upgrade/build/testrun/testAgainstTwoThirdsUpgradedCluster/temp/org.opensearch.neuralsearch.bwc.rolling.NeuralSparseSearchIT_E42B39786EA922E1-001
  2> NOTE: test params are: codec=Asserting(Lucene101): {}, docValues:{}, maxPointsInLeafNode=143, maxMBSortInHeap=6.3397129509832, sim=Asserting(RandomSimilarity(queryNorm=true): {}), locale=ff-Adlm-NE, timezone=BET
  2> NOTE: Linux 6.11.0-1015-azure amd64/Azul Systems, Inc. 23.0.2 (64-bit)/cpus=4,threads=2,free=463780136,total=536870912
  2> NOTE: All tests run in this JVM: [BatchIngestionIT, HybridSearchIT, HybridSearchRelevancyIT, HybridSearchWithRescoreIT, KnnRadialSearchIT, MultiModalSearchIT, NeuralQueryEnricherProcessorIT, NeuralSparseSearchIT]
NeuralSparseSearchIT > testSparseEncodingProcessor_E2EFlow FAILED
    org.junit.ComparisonFailure: expected:<[0]> but was:<[1]>
        at __randomizedtesting.SeedInfo.seed([E42B39786EA922E1:2617D9E173359055]:0)
        at org.junit.Assert.assertEquals(Assert.java:117)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at org.opensearch.neuralsearch.bwc.rolling.NeuralSparseSearchIT.validateTestIndexOnUpgrade(NeuralSparseSearchIT.java:115)
        at org.opensearch.neuralsearch.bwc.rolling.NeuralSparseSearchIT.testSparseEncodingProcessor_E2EFlow(NeuralSparseSearchIT.java:77)
  1> [2025-06-27T20:12:54,024][INFO ][o.o.n.b.r.NeuralSparseSearchIT] [testSparseEncodingProcessor_E2EFlow] before test
  1> [2025-06-27T20:12:54,026][INFO ][o.o.n.b.r.NeuralSparseSearchIT] [testSparseEncodingProcessor_E2EFlow] initializing REST clients against [http://[::1]:38[423](https://github.com/opensearch-project/neural-search/actions/runs/15937587620/job/44960472366?pr=1414#step:4:424), http://127.0.0.1:45299, http://[::1]:42875, http://127.0.0.1:35723, http://[::1]:38559, http://127.0.0.1:37337]
  1> [2025-06-27T20:12:54,123][INFO ][o.o.n.b.r.NeuralSparseSearchIT] [testSparseEncodingProcessor_E2EFlow] after test
```

### PR DESCRIPTION
**Pull request by zhichao-aws**
### Description

https://github.com/opensearch-project/neural-search/issues/1416

In current code,  the `MINIMAL_SUPPORTED_VERSION_ANALYZER` is v3.0. And it will cause serialization/deserialization issues in bwc tests. This PR fix the bug. 

### Related Issues
Resolves #1416 

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [ ] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/neural-search/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by heemin32 — APPROVED** [review]

File: src/main/java/org/opensearch/neuralsearch/query/NeuralSparseQueryBuilder.java [hunk 1]
```diff
@@ -111,7 +111,7 @@ public static void initialize(MLCommonsClientAccessor mlClient) {
     private NeuralSparseQueryTwoPhaseInfo neuralSparseQueryTwoPhaseInfo = new NeuralSparseQueryTwoPhaseInfo();
 
     private static final Version MINIMAL_SUPPORTED_VERSION_DEFAULT_MODEL_ID = Version.V_2_13_0;
-    private static final Version MINIMAL_SUPPORTED_VERSION_ANALYZER = Version.V_3_0_0;
+    private static final Version MINIMAL_SUPPORTED_VERSION_ANALYZER = Version.V_3_1_0;
```
Comment (owaiskazi19) [inline src/main/java/org/opensearch/neuralsearch/query/NeuralSparseQueryBuilder.java:114]: We should make this configurable to pick from bwc version otherwise we need to update this after every version released 
@heemin32 @zhichao-aws

Comment (heemin32) [reply src/main/java/org/opensearch/neuralsearch/query/NeuralSparseQueryBuilder.java:114]: It is not. This should have been V3.1.0 from the start. The feature is not released in V3.0.0
