### PR TITLE
Fix bug where document embedding fails to be generated due to document has dot in field name

### LINKED ISSUE #1042: [BUG] Fail to generate embedding for ingest document with nested field defined in field map
### What is the bug?
When field map is defined with nested field like `"a.b.c": "d.e"` for ingest pipeline, the ingestion for document with field in a list of `"a.b.c"` will fail the ingestion

### How can one reproduce the bug?
1. Create ingest pipeline
```
PUT /_ingest/pipeline/nlp-ingest-pipeline-v4

{
  "description": "text embedding pipeline example",
  "processors": [
    {
      "text_embedding": {
        "model_id": "AMT_KJQBWWsqXNqdQAfI",
        "field_map": {
          "nested_field.level1.level2": "level3.level4Embedding" 
				}
      }
    }
  ]
}


```

2. Simulate
```
POST /_ingest/pipeline/nlp-ingest-pipeline-v4/_simulate

{
	"docs": [
		{
			"_index": "neural-search-index-v2",
			"_id": "1",
			"_source": {
				"nested_field.level1": [
					{
						"level2": "hello"
					},
					{
						"level2": "world"
					}
				]
			}
		}
	]
}
```

3. Result
```
{
  "docs": [
    {
      "doc": {
        "_index": "neural-search-index-v2",
        "_id": "1",
        "_source": {
          "nested_field": [
	   {
              "level1": {
                  "level2": "hello"
               }
            },
	   {
              "level1": {
                  "level2": "world"
               }
            }
          ]
        },
        "_ingest": {
          "timestamp": "2025-01-02T22:45:34.884624Z"
        }
      }
    }
  ]
}
```

### What is the expected behavior?
Doc in `nested_field` list should have embedding fields like
```
{
  "docs": [
    {
      "doc": {
        "_index": "neural-search-index-v2",
        "_id": "1",
        "_source": {
          "nested_field": [
            {
              "level1": {
                  "level2": "hello",
                  "level3.level4Embedding": [
                    0.18129997,
                    -0.056219965,
                   ...
                  ]
               }
            },
            {
              "level1": {
                  "level2": "world",
                  "level3.level4Embedding": [
                    0.0358946,
                    0.04183194,
                   ...
                  ]
               }
            }
          ]
        },
        "_ingest": {
          "timestamp": "2025-01-02T22:51:03.541304Z"
        }
      }
    }
  ]
}
```

### What is your host/environment?
Mac OS

### Do you have any screenshots?
N/A

### Do you have any additional context?
N/A

### PR DESCRIPTION
**Pull request by yizheliu-amazon**
### Description
Fix bug where document embedding fails to be generated due to document has dot in field name, which does not match field mapping exactly

### Related Issues
Resolves #1042 

#### Root cause
Such issue is caused by that we fail to unbox/unflatten field in ingested doc, then it causes mismatch between nested field in fieldMap config and ingested document schema. 

For example, nested field can be represented as either {"a.b": "c"}, or {"a": {"b": "c"}}. If fieldMap is {"a": {"b": "b_embedding"}}, but ingested document is like {"a.b": "c"}, such schema mismatch fieldMap, and then we are not able to fetch "c" as value for inferencing. 

### About the change

Basically, the solution is to unbox/unflatten the field with dot from ingested doc.

Before this change, given fieldMap is below
```
{
  "description": "text embedding pipeline for exampe",
  "processors": [
    {
      "text_embedding": {
        "model_id": "EJTmBpQBz0MpoghfHptn",
        "field_map": {
          "nested_passages.level_2.level_3_text": "level_3_container.level_3_embedding"
        }
      }
    }
  ]
}
```
Simulate ingestion for below doc, there is no `level_3_container.level_3_embedding` generated for it.
```
{
  "docs": [
    {
      "_index": "neural-search-index-v2",
      "_id": "1",
      "_source": {
        "nested_passages": [
          {
            "level_2.level_3_text": "clown"
          },
          {
            "level_2": {
              "level_3_text": "batman"
            }
          }
        ]
      }
    }
  ]
}
```

After this change, embedding can be generated 
```
{
  "docs": [
    {
      "doc": {
        "_index": "neural-search-index-v2",
        "_id": "1",
        "_source": {
          "nested_passages": [
            {
              "level_2": {
                "level_3_container": {
                  "level_3_embedding": [
                    0.17990997,
                    0.064552955,
                    ...
                  ]
                },
                "level_3_text": "clown"
              }
            },
            {
              "level_2": {
                "level_3_container": {
                  "level_3_embedding": [
                    0.20891039,
                    0.09188991,
                    ...
                  ]
                },
                "level_3_text": "batman"
              }
            }
          ]
        },
        "_ingest": {
          "timestamp": "2025-01-06T19:00:12.84077Z"
        }
      }
    }
  ]
}
```

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/neural-search/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/test/java/org/opensearch/neuralsearch/util/ProcessorDocumentUtilsTests.java [hunk 1]
```diff
@@ -80,4 +83,150 @@ public void test_with_different_configurations() throws URISyntaxException, IOEx
         }
     }
 
+    public void test_unflatten_simple_dot_notation() {
```
Comment (heemin32) [inline src/test/java/org/opensearch/neuralsearch/util/ProcessorDocumentUtilsTests.java:86]: Could you make the test naming consistent with others?
`testUnflatten_whenSimpleDotNotation_thenSucceed`

File: src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorIT.java [hunk 2]
```diff
@@ -240,6 +258,56 @@ public void testTextEmbeddingProcessor_withFailureAndSkip() throws Exception {
...
+        try {
+            modelId = uploadTextEmbeddingModel();
+            loadModel(modelId);
+            createPipelineProcessor(modelId, PIPELINE_NAME, ProcessorType.TEXT_EMBEDDING_WITH_NESTED_FIELDS_MAPPING);
+            createTextEmbeddingIndex();
+            ingestDocument(INGEST_DOC5, "5");
+
+            assertDocWithLevel2AsList((Map<String, Object>) getDocById(INDEX_NAME, "5").get("_source"));
+
+            NeuralQueryBuilder neuralQueryBuilderQuery = new NeuralQueryBuilder(
```
Comment (will-hwang) [inline src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorIT.java:273]: can you merge main to this pr? `NeuralQueryBuilder` should be initialized with a builder contructor

File: src/test/java/org/opensearch/neuralsearch/util/ProcessorDocumentUtilsTests.java (hunk 1 above)
Comment (yizheliu-amazon) [reply src/test/java/org/opensearch/neuralsearch/util/ProcessorDocumentUtilsTests.java:86]: Sure. Will do.

Comment (will-hwang) [inline src/test/java/org/opensearch/neuralsearch/util/ProcessorDocumentUtilsTests.java:86]: can we add test cases for invalid input as well?

For example: `".a.b"` or `"a.b."`

Comment (yizheliu-amazon) [reply src/test/java/org/opensearch/neuralsearch/util/ProcessorDocumentUtilsTests.java:86]: That's a good point. Will add validation for invalid input, and corresponding test cases.

File: src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorIT.java (hunk 2 above)
Comment (yizheliu-amazon) [reply src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorIT.java:273]: Sure. will do.

**Review by heemin32 — APPROVED** [review]

**Review by junqiu-lei — APPROVED** [review]

**Review by will-hwang — APPROVED** [review]
