### PR TITLE
Handle exceptions gracefully when delete non-existent resources during integ test resource clean up

### LINKED ISSUE #1098: [Infrastructure] Wipe integration test resources and surface exceptions gracefully
Currently many of our integration tests for our processors (text embedding, text image embedding, sparse encoding) follow the following pattern to create and cleanup resources
```
public void processor_integrationTest() {
    try {
        // load model
        // create pipeline/index
        // do tests/asserts
    } finally {
        // cleanup pipeline, index, model
    }
}
```

However, this causes issues like #1091 where if the integration tests fail in the try block before creating the pipeline, it will enter the finally block and attempt to delete the nonexistent pipeline. This causes an exception in the cleanup and masks the true exception, such as #1093 where the root issue is a memory circuit breaker trigger which is unclear from the test report.

We should rework our integration test cleanup so we can:
- Log errors more clearly during resource cleanup to avoid confusion
- Resource cleanup after every test rather than a part of every test, so cleanup won't directly cause test failures

### PR DESCRIPTION
**Pull request by weijia-aws**
### Description
When integ test runs, the test will create model, index, pipeline, etc., then perform some assertions, finally clean up the resources. 

```
public void processor_integrationTest() {
    try {
        // load model
        // create pipeline/index
        // do tests/asserts
    } finally {
        // cleanup pipeline, index, model
    }
}
```

If somehow resource creation fail and receive an exception, the test will enter the finally block and try to delete the resources. Since these resources don't exist, exception will be thrown when try to delete them, see [issue 1091](https://github.com/opensearch-project/neural-search/issues/1091). I was able to reproduce the exception by following https://github.com/opensearch-project/neural-search/pull/1093#issuecomment-2590760941. So in this case, we should gracefully handle such NOT FOUND exceptions

### Related Issues
Resolves #1098 

Related issue: #1091 and #1093

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [ ] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/neural-search/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by heemin32** [comment]
Can we expand the scope of this PR to shift the responsibility for resource cleanup from individual tests to the framework? This way, each test wouldn’t need to handle resource cleanup individually.

**Comment by vibrantvarun** [comment]
> Can we expand the scope of this PR to shift the responsibility for resource cleanup from individual tests to the framework? This way, each test wouldn’t need to handle resource cleanup individually.

I would suggest not to do that. As Integ tests are meant to be run in isolation mode. With resource cleanup at framework level, it will create issues where test will start sharing resources with each other and can cause critical issues to be skipped at integ test level because the resource might be created by some other method and used by some other method.

**Review by vibrantvarun — APPROVED** [review]

**Comment by vibrantvarun** [comment]
LGTM

**Comment by minalsha** [comment]
https://github.com/opensearch-project/neural-search/pull/1154#issuecomment-2627908252

+1 to Varun's comment here.

**Comment by heemin32** [comment]
> @heemin32 I would suggest not to do that. As Integ tests are meant to be run in isolation mode. With resource cleanup at framework level, it will create issues where test will start sharing resources with each other and can cause critical issues to be skipped at integ test level because the resource might be created by some other method and used by some other method.

Have you seen any such issue in k-nn repo where the resource clean up is handling in framework level? The resource sharing issue can happen when clean up is happening in individual test level when developer missed to clean up the resource in a test.

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java [hunk 1]
```diff
@@ -1504,23 +1505,32 @@ protected void wipeOfTestResources(
...
+            }
+            if (indexName != null) {
+                deleteIndex(indexName);
+            }
+        } catch (ResponseException e) {
+            // It's possible that test fails during resources (index, model, pipeline, etc.) creation, when clean up
+            // these resources after test run, the delete methods will throw ResponseException with 404 Not Found code
+            // In this case, we just need to ignore this exception, for other exceptions, continue throwing
+            if (RestStatus.fromCode(e.getResponse().getStatusLine().getStatusCode()) != RestStatus.NOT_FOUND) {
+                throw e;
```
Comment (heemin32) [inline src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1532]: This exception will still obscure the original exception. Therefore, I believe resource cleanup should be managed in the `@After` method rather than in the `finally` block.

Comment (vibrantvarun) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1532]: So are you saying we should shift this cleanUp at every integ class level?

Comment (vibrantvarun) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1532]: When I developed the framework you suggested to do it in in current way https://github.com/opensearch-project/neural-search/pull/533#discussion_r1465646182

Comment (heemin32) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1532]: cleanUp at every individual test level but inside base class so that each test class don't repeat the same code. https://github.com/opensearch-project/k-NN/blob/main/src/testFixtures/java/org/opensearch/knn/ODFERestTestCase.java#L152

Comment (vibrantvarun) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1532]: So it will mean just removal of code under finally block and move it in @After. The cleanUp method will go to base class so it in a particular integ class it will look little better. But underlying work still remains the same

Comment (vibrantvarun) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1532]: Is my understand correct?

Comment (heemin32) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1532]: Yes. However, there is one more difference. When it fails inside @after method, it won't obscure the exception thrown during test I believe?

Comment (weijia-aws) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1532]: > This exception will still obscure the original exception.

Yes, the original exception was overriden by the exception that thrown in the finally block, hence we were not able to see the original exception in the first place. 

I will make more code change to remove the finally block and add it to an @After method

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java [hunk 2]
```diff
@@ -1504,23 +1505,32 @@ protected void wipeOfTestResources(
...
-        }
-        if (modelId != null) {
-            try {
-                deleteModel(modelId);
-            } catch (AssertionError e) {
-                // sometimes we have flaky test that the model state doesn't change after call undeploy api
-                // for this case we can call undeploy api one more time
-                deleteModel(modelId);
+        try {
+            if (ingestPipeline != null) {
```
Comment (q-andy) [inline src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1509]: I agree with the discussion below to move cleanup to an @After block, but I want to point out that the root cause is that our integ tests call this method and pass in static constant Strings directly into ingestPipeline/searchPipeline/indexName regardless of whether or not the resources were created like here: https://github.com/opensearch-project/neural-search/blob/main/src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorIT.java#L76

In those conditions these blocks are never triggered. Not saying we need to change that right now, but pointing out with an @After block we still don't address the root cause here, just move the exception where we can't see it?

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java (hunk 1 above)
Comment (q-andy) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1532]: Even if we move to @after block the root issue is that we shouldn't be calling this method passing in resources we haven't created yet right? The method is still called incorrectly, we just hide the exception?

Comment (heemin32) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1532]: > Even if we move to @after block the root issue is that we shouldn't be calling this method passing in resources we haven't created yet right? The method is still called incorrectly, we just hide the exception?

You are right. When we moved to @after block, we won't depend on static value of resource name but we will make an api call to list all available resources and clean them up.

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java [hunk 3]
```diff
@@ -1410,6 +1427,80 @@ protected void reindex(String fromIndexName, String toIndexName) throws Exceptio
...
+    }
+
+    /**
+     * Retrieve all existing pipelines or a specific pipeline
+     * @param pipelineType _ingest for retrieving ingest pipelines, _search for retrieving search pipelines
+     * @param pipelineName a specific pipeline to retrieve, if value is empty, it returns all pipelines
+     * @return get pipeline response as a map object
+     */
+    @SneakyThrows(ParseException.class)
+    protected Map<String, Object> retrievePipelines(final String pipelineType, final String pipelineName) throws IOException {
```
Comment (q-andy) [inline src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1485]: Great work, I'm curious if there's any increased latency for the integ tests by adding extra get requests per test? Is the runtime for all the integ tests impacted?

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java [hunk 4]
```diff
@@ -1410,6 +1427,80 @@ protected void reindex(String fromIndexName, String toIndexName) throws Exceptio
...
+    }
+
+    /**
+     * Fetch all existing indices and clean up, note that some system generated indices are skipped
+     */
+    protected void deleteExistingIndices() throws IOException {
+        List<Map<String, Object>> indices = retrieveIndices();
+        for (Map<String, Object> index : indices) {
+            final String indexName = (String) index.get("index");
+            if (!shouldDeleteIndex(indexName)) {
```
Comment (weijia-aws) [inline src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1465]: I will rename this method to `shouldNotDeleteIndex`

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java (hunk 3 above)
Comment (heemin32) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1485]: The latency should be minimal and it is generally okay to have some slowness for testing.

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java [hunk 5]
```diff
@@ -1498,29 +1651,40 @@ protected Float getFeatureFieldCompressedNumber(final Float originNumber) {
...
     // Wipe of all the resources after execution of the tests.
-    protected void wipeOfTestResources(
-        final String indexName,
-        final String ingestPipeline,
-        final String modelId,
-        final String searchPipeline
-    ) throws IOException {
-        if (ingestPipeline != null) {
-            deletePipeline(ingestPipeline);
+    protected void wipeOfTestResources() throws IOException {
```
Comment (heemin32) [inline src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1654]: Can we remove this method entirely so that people don't call this explicitly?

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java [hunk 6]
```diff
@@ -1498,29 +1651,40 @@ protected Float getFeatureFieldCompressedNumber(final Float originNumber) {
...
+        try {
+            deleteExistingIngestionPipelines();
+        } catch (ResponseException e) {
+            // It's possible that test fails during resources (index, model, pipeline, etc.) creation, when clean up
+            // these resources after test run, the delete methods will throw ResponseException with 404 Not Found code
+            // In this case, we just need to ignore this exception, for other exceptions, continue throwing
+            if (RestStatus.NOT_FOUND != RestStatus.fromCode(e.getResponse().getStatusLine().getStatusCode())) {
```
Comment (heemin32) [inline src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1661]: Now we don't need to consume not found exception silently.

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java [hunk 7]
```diff
@@ -1410,6 +1427,80 @@ protected void reindex(String fromIndexName, String toIndexName) throws Exceptio
...
+
+    /**
+     * Retrieve all existing pipelines or a specific pipeline
+     * @param pipelineType _ingest for retrieving ingest pipelines, _search for retrieving search pipelines
+     * @param pipelineName a specific pipeline to retrieve, if value is empty, it returns all pipelines
+     * @return get pipeline response as a map object
+     */
+    @SneakyThrows(ParseException.class)
+    protected Map<String, Object> retrievePipelines(final String pipelineType, final String pipelineName) throws IOException {
+        Request request = new Request("GET", "/" + pipelineType + "/pipeline/" + (StringUtils.isEmpty(pipelineName) ? "" : pipelineName));
```
Comment (junqiu-lei) [inline src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1486]:
```suggestion
    String endpoint = String.format("/%s/pipeline/%s", pipelineType, 
        Optional.ofNullable(pipelineName).orElse(""));
    Request request = new Request("GET", endpoint);
```

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java (hunk 5 above)
Comment (weijia-aws) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1654]: Sure

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java (hunk 3 above)
Comment (weijia-aws) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1485]: So I ran the integ tests with and without this commit. Total runtime is:

Previous: 8m3.59s
Now: 8m2.34s 

The latency is really minimal

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java (hunk 6 above)
Comment (weijia-aws) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1661]: We still need it, at least for pipelines. If there's no pipeline exists, and we make a get pipelines call, the API will throw us this exception. There's an issue opened as well in core: https://github.com/opensearch-project/OpenSearch/issues/15917

Comment (heemin32) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1661]: However, do we make get call for non existing pipeline?

Comment (weijia-aws) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1661]: There're some test cases that don't create ingest pipeline, such as this [one](https://github.com/opensearch-project/neural-search/blob/main/src/test/java/org/opensearch/neuralsearch/query/HybridQuerySortIT.java), there're some test cases that don't create search pipeline, such as [this](https://github.com/opensearch-project/neural-search/blob/main/src/test/java/org/opensearch/neuralsearch/query/NeuralQueryIT.java). Since we want to run this clean up method after every test, we need to make a get call for every resource

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java (hunk 7 above)
Comment (weijia-aws) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1486]: Good suggestion, this is more readable for handling null values, but it's not able to handle strings with empty space.  However I think it is fine as this is only used in Integ tests. Will adopt the suggestion

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java (hunk 6 above)
Comment (heemin32) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1661]: However, don't we call list pipeline API to get all available pipeline instead of getting individual pipline by its name?

Comment (weijia-aws) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1661]: We do call the API to get all available pipelines, and it throws exception if none exist

Comment (weijia-aws) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1661]: If [this issue](https://github.com/opensearch-project/OpenSearch/issues/15917) can be closed, then we don't have to handle this exception

Comment (heemin32) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1661]: Can we handle that exception inside a method to get a list of pipeline instead of here?

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java [hunk 8]
```diff
@@ -1498,29 +1651,40 @@ protected Float getFeatureFieldCompressedNumber(final Float originNumber) {
...
-                deleteModel(modelId);
-            } catch (AssertionError e) {
-                // sometimes we have flaky test that the model state doesn't change after call undeploy api
-                // for this case we can call undeploy api one more time
-                deleteModel(modelId);
+
+        try {
+            deleteExistingModels();
+        } catch (ResponseException e) {
+            if (RestStatus.NOT_FOUND != RestStatus.fromCode(e.getResponse().getStatusLine().getStatusCode())) {
```
Comment (heemin32) [inline src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1677]: I guess we don't need this condition check?

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java [hunk 9]
```diff
@@ -1498,29 +1651,40 @@ protected Float getFeatureFieldCompressedNumber(final Float originNumber) {
...
+                throw e;
             }
         }
-        if (indexName != null) {
-            deleteIndex(indexName);
+
+        try {
+            deleteExistingIndices();
+        } catch (ResponseException e) {
+            if (RestStatus.NOT_FOUND != RestStatus.fromCode(e.getResponse().getStatusLine().getStatusCode())) {
```
Comment (heemin32) [inline src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1685]: I guess we don't need this condition check?

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java [hunk 10]
```diff
@@ -1498,29 +1651,40 @@ protected Float getFeatureFieldCompressedNumber(final Float originNumber) {
...
+                throw e;
+            }
         }
-        if (searchPipeline != null) {
-            deleteSearchPipeline(searchPipeline);
+
+        try {
+            deleteExistingSearchPipelines();
+        } catch (ResponseException e) {
+            if (RestStatus.NOT_FOUND != RestStatus.fromCode(e.getResponse().getStatusLine().getStatusCode())) {
```
Comment (heemin32) [inline src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1669]: Same as above.

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java (hunk 6 above)
Comment (weijia-aws) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1661]: Of course

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java (hunk 10 above)
Comment (weijia-aws) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1669]: We don't need it if we move the exception handling logic to the get call

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java (hunk 8 above)
Comment (weijia-aws) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:1677]: No, will remove

**Review by heemin32 — COMMENTED** [review]
LGTM. Thanks!

**Review by heemin32 — DISMISSED** [review]

**Comment by heemin32** [comment]
Test is failing. Please take a look.

**Comment by weijia-aws** [comment]
> Test is failing. Please take a look.

qa tests are failing because: testAgainstNewCluster depends on resources that created in testAgainstOldCluster, however when testAgainstOldCluster finishes, all resources are cleaned up, resulting in testAgainstNewCluster tests fail with `java.lang.NullPointerException` or Resource not found exception. In order to fix this, we will need to re-create resources in testAgainstNewCluster tasks

**Comment by weijia-aws** [comment]
> In order to fix this, we will need to re-create resources in testAgainstNewCluster tasks

We can also modify the cleanUp method to not delete resources if running against old cluster?

**Comment by weijia-aws** [comment]
> We can also modify the cleanUp method to not delete resources if running against old cluster?

I think we should do this, as this is how the current behavior is, and requires less code changes comparing to re-create resources

File: qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/HybridSearchIT.java [hunk 11]
```diff
@@ -55,30 +55,28 @@ public void testNormalizationProcessor_whenIndexWithSingleShard_E2EFlow() throws
...
         throws Exception {
         waitForClusterHealthGreen(NODES_BWC_CLUSTER);
+        super.ingestPipelineName = pipelineName;
+        super.searchPipelineName = searchPipelineName;
+
         if (isRunningAgainstOldCluster()) {
-            String modelId = uploadTextEmbeddingModel();
-            loadModel(modelId);
-            createPipelineProcessor(modelId, pipelineName);
+            super.modelId = uploadTextEmbeddingModel();
```
Comment (heemin32) [inline qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/HybridSearchIT.java:62]: I suggest not making any changes to the BWC tests, as this approach may not work. For instance, there are two tests: `testNormalizationProcessor_whenIndexWithMultipleShards_E2EFlow` and `testNormalizationProcessor_whenIndexWithSingleShard_E2EFlow`. Each test uploads a model, but the model ID from the previous test is overwritten by the next, resulting in a failure to delete the all resources.

Comment (weijia-aws) [reply qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/HybridSearchIT.java:62]: I don't think the resources deletion logic is changed. I simply moved the cleanup logic from finally block to an After class method. In order to do that, we just need to set the resource names according. 

> but the model ID from the previous test is overwritten by the next

The model gets cleanup already when the test finishes, so it's fine and has to be overwritten

Comment (heemin32) [reply qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/HybridSearchIT.java:62]: > The model gets cleanup already when the test finishes, so it's fine and has to be overwritten

In old cluster, 
Test 1 create model A and set super.modelId. The test complete without deleting the model.
Test 2 create model B and override super.modelId. The test complete without deleting the model.

In new cluster,
Test 1 use model B because modelId is overwritten by Test 2. The test complete. If model B deletion happen here before test 2, the test 2 might fail because there is no model B.
Test 2 use model B. The test complete. Delete the model B.

Now, the model A stay without being deleted.

Comment (weijia-aws) [reply qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/HybridSearchIT.java:62]: In new cluster, we are getting model id by pipeline name then assign the value of `super.modelId`, since model A and model B are created in different pipelines, we shouldn't get the wrong model in the new cluster for these two test cases? The behavior is the same before this commit, see [code](https://github.com/opensearch-project/neural-search/blob/main/qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/HybridSearchIT.java#L72C27-L72C37)

Comment (weijia-aws) [reply qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/HybridSearchIT.java:62]: Each test is still isolated, it's just we need to update the resource name for each test case so that resources can be properly clean up. I agree this is error-prone as we need to maintain the value assignment logic for each test. But this approach align with the purpose of this issue.

How about we move the After method to each test class instead of the base class? will it make the logic clearer?

Comment (heemin32) [reply qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/HybridSearchIT.java:62]: Yes. It is isolated in class level. However, it is not isolated in method level. That being said, moving After method to each test class has no difference.

I understand that bwc also has similar issue where the exception during resource clean up will disguise the original exception. However, the nature of how bwc test works is completely different from integ test. We might need to think better option than this.

One option is creating another gradle task for resource clean up which will be executed after all tests are completed.

We can close this PR by focusing only in integ test but not bwc test. For bwc test, we can handle in other PR.

Comment (weijia-aws) [reply qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/HybridSearchIT.java]: Sounds good, glad we have another PR to fix

Comment (weijia-aws) [reply qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/HybridSearchIT.java]: Resolving the conversation as new commit is published

**Review by heemin32 — APPROVED** [review]
LGTM. Thanks!

**Comment by heemin32** [comment]
The failure in bwc is a known issue.
https://github.com/opensearch-project/neural-search/issues/1142
