### PR TITLE
Disable ML-Commons disk circuit breaker in tests

### LINKED ISSUE #1494: [Failing Test] BWC testBatchIngestionWithNeuralSparseProcessor_E2EFlow
```
REPRODUCE WITH: ./gradlew ':qa:restart-upgrade:testAgainstNewCluster' --tests 'org.opensearch.neuralsearch.bwc.restart.BatchIngestionIT.testBatchIngestionWithNeuralSparseProcessor_E2EFlow' -Dtests.seed=D3317EEB6505E4BD -Dtests.security.manager=false -Dtests.bwc.version=2.20.0-SNAPSHOT -Dtests.locale=lb-Latn-LU -Dtests.timezone=Kwajalein -Druntime.java=21
  2> java.lang.AssertionError: expected:<10> but was:<5>
        at __randomizedtesting.SeedInfo.seed([D3317EEB6505E4BD:F6114276F629F30]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.opensearch.neuralsearch.BaseNeuralSearchIT.validateDocCountAndInfo(BaseNeuralSearchIT.java:2488)
        at org.opensearch.neuralsearch.bwc.restart.BatchIngestionIT.testBatchIngestionWithNeuralSparseProcessor_E2EFlow(BatchIngestionIT.java:45)
```

### PR DESCRIPTION
**Pull request by chishui**
### Description
Many tests fails as disk circuit breaker is triggered in ML Commons. Disable this setting.

### Related Issues
Resolves #1494

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/neural-search/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java [hunk 1]
```diff
@@ -136,6 +138,7 @@ public abstract class BaseNeuralSearchIT extends OpenSearchSecureRestTestCase {
     private static final Set<RestStatus> SUCCESS_STATUSES = Set.of(RestStatus.CREATED, RestStatus.OK);
     protected static final String CONCURRENT_SEGMENT_SEARCH_ENABLED = "search.concurrent_segment_search.enabled";
     protected static final String RRF_SEARCH_PIPELINE = "rrf-search-pipeline";
+    protected static final Version DISK_CIRCUIT_BREAKER_SUPPORTED_VERSION = Version.fromString("2.16.0");
```
Comment (yuye-aws) [inline src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java]: Can you provide more context on why you choose this version?

Comment (chishui) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java]: This feature was introduced in 2.16

Comment (heemin32) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java]:
```suggestion
    protected static final Version DISK_CIRCUIT_BREAKER_SUPPORTED_VERSION = Version.V_2_16_0;
```

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java [hunk 2]
```diff
@@ -198,6 +201,14 @@ protected void updateClusterSettings() {
         updateClusterSettings("plugins.ml_commons.jvm_heap_memory_threshold", 95);
         updateClusterSettings("plugins.ml_commons.allow_registering_model_via_url", true);
 
+        Optional<String> bwcVersion = Optional.ofNullable(System.getProperty(BWC_VERSION, null));
```
Comment (yuye-aws) [inline src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java]: nit: I would suggest moving the following function from **AbstractRestartUpgradeRestTestCase** and **AbstractRollingUpgradeTestCase** to **BaseNeuralSearchIT** to reduce code duplication

```
    protected final Optional<String> getBWCVersion() {
        return Optional.ofNullable(System.getProperty(BWC_VERSION, null));
    }
```

Comment (chishui) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java]: It's just one line, you don't save any codes actually. I feel it quite makes sense to keep them in BWC as it's close to the logic where it's used.

**Comment by chishui** [comment]
https://github.com/opensearch-project/neural-search/actions/runs/16848282935/job/47730932246?pr=1504
```
org.opensearch.client.ResponseException: method [GET], host [http://127.0.0.1:39157/], URI [/_cluster/health?wait_for_nodes=3&timeout=60s&wait_for_status=green&cluster_manager_timeout=60s], status line [HTTP/1.1 408 Request Timeout]
    {"cluster_name":"neuralSearchBwcCluster-rolling","status":"yellow","timed_out":true,"number_of_nodes":3,"number_of_data_nodes":3,"discovered_master":true,"discovered_cluster_manager":true,"active_primary_shards":40,"active_shards":79,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":2,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":97.53086419753086}
        at __randomizedtesting.SeedInfo.seed([4EE6A7331EDB7C37:C1A36AA9B2DD3AE0]:0)
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:501)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:384)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:359)
        at app//org.opensearch.neuralsearch.BaseNeuralSearchIT.waitForClusterHealthGreen(BaseNeuralSearchIT.java:2046)
        at app//org.opensearch.neuralsearch.BaseNeuralSearchIT.waitForClusterHealthGreen(BaseNeuralSearchIT.java:2052)
        at
```

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java (hunk 2 above)
Comment (yuye-aws) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java]: Agree that this is close to the BWC logic. To me, I think this PR is fixing the BWC test. The base IT is about all the ITs. Can you add this logic to the BWC test including rolling upgrade and restart upgrade?

Comment (chishui) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java]: This is the place where cluster setting is configured, it's shared by integ test and BWC tests, although, the setting I added checked BWC version, it's just to limit the scope of my change. Later, we could apply this to all tests, I don't think it's necessary to move it to BWC tests

**Comment by heemin32** [comment]
Please fix the failing tests.

**Comment by chishui** [comment]
> Please fix the build failure.

now the only failed BWC tests will be fixed by #1503

**Comment by heemin32** [comment]
> > Please fix the build failure.
> 
> now the only failed BWC tests will be fixed by #1503

I still see it failed with circuit breaker issue.

```
org.opensearch.core.common.breaker.CircuitBreakingException: Disk Circuit Breaker is open, please check your resources!
»  	at org.opensearch.ml.utils.MLNodeUtils.checkOpenCircuitBreaker(MLNodeUtils.java:138) ~[?:?]
»  	at org.opensearch.ml.task.MLTaskRunner.checkCBAndExecute(MLTaskRunner.java:134) ~[?:?]
»  	at org.opensearch.ml.task.MLTaskRunner.run(MLTaskRunner.java:90) ~[?:?]
```

**Comment by chishui** [comment]
> > > Please fix the build failure.
> > 
> > 
> > now the only failed BWC tests will be fixed by #1503
> 
> I still see it failed with circuit breaker issue.
> 
> ```
> org.opensearch.core.common.breaker.CircuitBreakingException: Disk Circuit Breaker is open, please check your resources!
> »  	at org.opensearch.ml.utils.MLNodeUtils.checkOpenCircuitBreaker(MLNodeUtils.java:138) ~[?:?]
> »  	at org.opensearch.ml.task.MLTaskRunner.checkCBAndExecute(MLTaskRunner.java:134) ~[?:?]
> »  	at org.opensearch.ml.task.MLTaskRunner.run(MLTaskRunner.java:90) ~[?:?]
> ```

Yes, that PR is not merged, I fix these two issues in two separate CRs, so we need to merge this PR first, then rebase the other, and merge that one later.

**Review by yuye-aws — APPROVED** [review]
Approving this PR since now all the checks are passed

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java [hunk 3]
```diff
@@ -216,10 +219,32 @@ protected void updateClusterSettings(final String settingKey, final Object value
...
+        try {
+            return makeRequest(
+                client(),
+                "PUT",
+                "_cluster/settings",
+                null,
+                toHttpEntity(builder.toString()),
+                ImmutableList.of(new BasicHeader(HttpHeaders.USER_AGENT, ""))
+            );
+        } catch (Exception e) {
```
Comment (heemin32) [inline src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:242]: It would be better to call this setting update only when the minimum cluster version is 2.16b and above.

Alternatively, we could catch the exception specifically when the setting is not supported, but not for other types of exceptions. For those other exceptions, it would be helpful to log the full exception for debugging purposes.

Comment (bzhangam) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:242]: I think we have tried update the setting only when the minimum cluster version is 2.16b and above. But it will fail for rolling upgrade. If some nodes are upgraded and the minimum cluster version is still lower than 2.16 then we will not update the setting. The upgraded nodes will run into the issue.

Comment (heemin32) [reply src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:242]: > It fails because I check BWC version which is always old version even when running testingAgainstNewCluster

I think, ml common should have enabled disk circuit breaker only when the min version is 2.16 and above? Previously, we didn't check the min version but only the old version I believe?
