### PR TITLE
Fix nested field missing sub embedding field

### LINKED ISSUE #909: [BUG] Nested field missing sub embedding field will cause the IndexOutOfBoundsException
### What is the bug?
Currently, if a nested field `nestedField` with two sub field `textField` and `textFieldNotForEmbedding`, and a doc like:

```
{
  "nestedField": [
    {
      "textFieldNotForEmbedding": "This is a text field"
    },
    {
      "textField": "This is another text field"
    }
  ]
}
```

applying pipeline configuration:

```
{
  "description": ...,
  "processors": [
    {
      "text_embedding": {
        "model_id": ...,
        "field_map": {
          "nestedField": {
              "textField": "vectorField"
          }
        }
      }
    }
  ]
}
```

Result:
```
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
```

Expected result:
```
{
  "nestedField": [
    {
      "textFieldNotForEmbedding": "This is a text field"
    },
    {
      "textField": "This is another text field"
      "vectorField": [...]
    }
  ]
}
```

### How can one reproduce the bug?
Change the mock doc in [test code](https://github.com/opensearch-project/neural-search/blob/main/src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java#L1032):
```
// textField --> textFieldNotForEmbedding

nestedObj1.put("textFieldNotForEmbedding", "This is a text field") 
```

In [unit test](https://github.com/opensearch-project/neural-search/blob/main/src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java#L728), get the nlpResult from `textEmbeddingProcessor.buildNLPResult`, then set it to each field in original doc just like the embedding processor actually does:
```
Map<String, Object> nlpResult = textEmbeddingProcessor.buildNLPResult(
            knnMap,
            modelTensorList,
            ingestDocument.getSourceAndMetadata()
        );
nlpResult.forEach(ingestDocument::setFieldValue);
```

And run the unit test with:
```
./gradlew ':test' --tests "org.opensearch.neuralsearch.processor.TextEmbeddingProcessorTests.testBuildVectorOutput_withNestedList_successful"
```

### What is the expected behavior?
Mentioned above.

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

### PR DESCRIPTION
**Pull request by wdongyu**
### Description
Detail description in #909, this pull add empty check before filling in the result

### Related Issues
Resolves #909 

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/neural-search/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by martin-gaievski** [comment]
@wdongyu is this PR is work in progress or ready for review? bunch of tests are failing...

**Comment by wdongyu** [comment]
@martin-gaievski will rerun and fix them... :(

**Comment by yuye-aws** [comment]
@wdongyu Can you check failing CIs: https://github.com/opensearch-project/neural-search/actions/runs/10987606139/job/30536408453?pr=913?

**Comment by wdongyu** [comment]
@yuye-aws working in process, I have found the problem and try to reproduce it on my dev box. It's related to the inference text which is null but sent to mlCommonsClientAccessor

**Comment by yuye-aws** [comment]
Great! Looking forward to see your new commits.

**Comment by wdongyu** [comment]
In the last commit, I have done:

1. Filter out the null entry in createInferenceListForMapTypeInput, so that we can avoid sending null inference text to mlCommonsClientAccessor. 
2. **Not filter out** the null entry in createInferenceList when `sourceValue instanceof List`, because if there exists any null entry for List, an IllegalArgumentException will be thrown, I also add a test to confirm that.
```
private List<String> createInferenceList(Map<String, Object> knnKeyMap) {
   ...
        if (sourceValue instanceof List) {
            texts.addAll(((List<String>) sourceValue));   --> not filter out null entry
        } else if (sourceValue instanceof Map) {
            createInferenceListForMapTypeInput(sourceValue, texts);    --> filter out null entry
        } 
   ...
}
```
3. Refine two tests, one is to make sure the failed doc count is corrected, another is to make sure the model is uploaded completely.

Please correct me if I am wrong. @martin-gaievski @yuye-aws

**Comment by yuye-aws** [comment]
Thanks! Will review this CR tomorrow. @martin-gaievski please start the CI workflow.

File: src/main/java/org/opensearch/neuralsearch/processor/InferenceProcessor.java [hunk 1]
```diff
@@ -419,8 +419,14 @@ private void putNLPResultToSourceMapForMapType(
             for (Map.Entry<String, Object> inputNestedMapEntry : ((Map<String, Object>) sourceValue).entrySet()) {
                 if (sourceAndMetadataMap.get(processorKey) instanceof List) {
                     // build nlp output for list of nested objects
+                    List<Object> inputNestedMapValue = (List<Object>) inputNestedMapEntry.getValue();
+                    int valueIndex = 0;
```
Comment (yuye-aws) [inline src/main/java/org/opensearch/neuralsearch/processor/InferenceProcessor.java:423]: Why do we need `valueIndex`? You can simply iterate over the whole list

File: src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java [hunk 2]
```diff
@@ -203,6 +203,7 @@ protected void loadModel(final String modelId) throws Exception {
             isComplete = checkComplete(taskQueryResult);
             Thread.sleep(DEFAULT_TASK_RESULT_QUERY_INTERVAL_IN_MILLISECOND);
         }
+        assertTrue(isComplete);
```
Comment (yuye-aws) [inline src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java:206]: Nice catch!

**Comment by yuye-aws** [comment]
@wdongyu Please run `./gradlew spotlessapply` to fix linting isssue

File: src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java [hunk 3]
```diff
@@ -730,7 +730,7 @@ public void testBuildVectorOutput_withNestedList_successful() {
         IngestDocument ingestDocument = createNestedListIngestDocument();
         TextEmbeddingProcessor textEmbeddingProcessor = createInstanceWithNestedMapConfiguration(config);
         Map<String, Object> knnMap = textEmbeddingProcessor.buildMapWithTargetKeys(ingestDocument);
-        List<List<Float>> modelTensorList = createMockVectorResult();
+        List<List<Float>> modelTensorList = createRandomOneDimensionalMockVector(2, 2, 0.0f, 1.0f);
```
Comment (yuye-aws) [inline src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java:733]: Can you tell me why making this change?

File: src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java [hunk 4]
```diff
@@ -739,12 +739,26 @@ public void testBuildVectorOutput_withNestedList_successful() {
...
+        assertNotNull(nestedObj.get(1).get("vectorField"));
+    }
+
     public void testBuildVectorOutput_withNestedList_Level2_successful() {
         Map<String, Object> config = createNestedList2LevelConfiguration();
         IngestDocument ingestDocument = create2LevelNestedListIngestDocument();
         TextEmbeddingProcessor textEmbeddingProcessor = createInstanceWithNestedMapConfiguration(config);
         Map<String, Object> knnMap = textEmbeddingProcessor.buildMapWithTargetKeys(ingestDocument);
-        List<List<Float>> modelTensorList = createMockVectorResult();
+        List<List<Float>> modelTensorList = createRandomOneDimensionalMockVector(2, 2, 0.0f, 1.0f);
```
Comment (yuye-aws) [inline src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java:761]: Same above

File: src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java [hunk 5]
```diff
@@ -739,12 +739,26 @@ public void testBuildVectorOutput_withNestedList_successful() {
...
     }
 
+    public void testBuildVectorOutput_withNestedListHasNotForEmbeddingField_successful() {
+        Map<String, Object> config = createNestedListConfiguration();
+        IngestDocument ingestDocument = createNestedListWithNotEmbeddingFieldIngestDocument();
+        TextEmbeddingProcessor textEmbeddingProcessor = createInstanceWithNestedMapConfiguration(config);
+        Map<String, Object> knnMap = textEmbeddingProcessor.buildMapWithTargetKeys(ingestDocument);
+        List<List<Float>> modelTensorList = createRandomOneDimensionalMockVector(1, 2, 0.0f, 1.0f);
+        textEmbeddingProcessor.buildNLPResult(knnMap, modelTensorList, ingestDocument.getSourceAndMetadata());
+        List<Map<String, Object>> nestedObj = (List<Map<String, Object>>) ingestDocument.getSourceAndMetadata().get("nestedField");
```
Comment (yuye-aws) [inline src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java:749]: Better to add @SuppressWarnings("unchecked") to this line

File: src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java [hunk 6]
```diff
@@ -754,6 +768,21 @@ public void testBuildVectorOutput_withNestedList_Level2_successful() {
...
 
+    public void testBuildVectorOutput_withNestedListHasNotForEmbeddingField_Level2_successful() {
+        Map<String, Object> config = createNestedList2LevelConfiguration();
+        IngestDocument ingestDocument = create2LevelNestedListWithNotEmbeddingFieldIngestDocument();
+        TextEmbeddingProcessor textEmbeddingProcessor = createInstanceWithNestedMapConfiguration(config);
+        Map<String, Object> knnMap = textEmbeddingProcessor.buildMapWithTargetKeys(ingestDocument);
+        List<List<Float>> modelTensorList = createRandomOneDimensionalMockVector(1, 2, 0.0f, 1.0f);
+        textEmbeddingProcessor.buildNLPResult(knnMap, modelTensorList, ingestDocument.getSourceAndMetadata());
+        Map<String, Object> nestedLevel1 = (Map<String, Object>) ingestDocument.getSourceAndMetadata().get("nestedField");
+        List<Map<String, Object>> nestedObj = (List<Map<String, Object>>) nestedLevel1.get("nestedField");
```
Comment (yuye-aws) [inline src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java:779]: Same above

File: src/main/java/org/opensearch/neuralsearch/processor/InferenceProcessor.java (hunk 1 above)
Comment (wdongyu) [reply src/main/java/org/opensearch/neuralsearch/processor/InferenceProcessor.java:423]: Make sense, will change to iterator style.

File: src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java (hunk 3 above)
Comment (wdongyu) [reply src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java:733]: In former createMockVectorResult, it always return 7 results. In this test case, we only send one inference text and want single result to return. If it return more than one result, we can't trigger the IndexOutOfBoundsException, so that we should control the number of vectors it return.

**Comment by vibrantvarun** [comment]
Triggered checks. I will review the PR today

**Comment by wdongyu** [comment]
Resolve all above conversations @yuye-aws @martin-gaievski @vibrantvarun

**Comment by yuye-aws** [comment]
Good. Taking a look

**Comment by yuye-aws** [comment]
The code looks good to me. Thanks for the contribution @wdongyu . Can @martin-gaievski or @vibrantvarun start the CI workflow?

**Comment by martin-gaievski** [comment]
Changes looks good to me, thank you! @wdongyu can you please rebase on main? you need to have changes from https://github.com/opensearch-project/neural-search/pull/916 in order to fix the CI. Once that's done and CI is green I'll approve and merge this PR.

**Comment by vibrantvarun** [comment]
LGTM

**Comment by wdongyu** [comment]
Rebase done, please start the CI workflow when you are available @martin-gaievski @vibrantvarun.

**Comment by yuye-aws** [comment]
> Rebase done, please start the CI workflow when you are available @martin-gaievski @vibrantvarun.

Thank you! CI is running now. Will approve your PR once the CI gets all passed.

**Comment by yuye-aws** [comment]
Hi @wdongyu ! I do not think you have missed anything. The following error log seems to be a problem from k-NN repo. Might have time to check it tomorrow.
```
        Caused by:
        java.lang.ExceptionInInitializerError: Exception java.util.ServiceConfigurationError: org.apache.lucene.codecs.Codec: Provider org.opensearch.knn.index.codec.KNN910Codec.KNN910Codec could not be instantiated [in thread "SUITE-MLCommonsClientAccessorTests-seed#[E12FC70B18037AED]-worker"]
            at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
            at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813)
            at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729)
            at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403)
            at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:68)
            at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:52)
            at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:38)
            at org.apache.lucene.codecs.Codec$Holder.<clinit>(Codec.java:45)
            ... 18 more
```

**Comment by yuye-aws** [comment]
A PR has been merged into the k-NN repo: https://github.com/opensearch-project/k-NN/pull/2195. Rerunning the CI now...

**Comment by martin-gaievski** [comment]
You need to wait for https://github.com/opensearch-project/neural-search/pull/927 to be merged, CI will keep failing until then

**Comment by yuye-aws** [comment]
https://github.com/opensearch-project/neural-search/pull/927 gets merged. Rerunning the CI now.

**Review by yuye-aws — APPROVED** [review]
All CI checks have passed. Thanks for your patience and contribution @wdongyu !

**Review by martin-gaievski — APPROVED** [review]
All good, thanks for contribution.

**Comment by wdongyu** [comment]
With many thanks for all of you.
