### PR TITLE
Fix issue where remote symmetric models are not supported

### LINKED ISSUE #1765: [BUG]: ingestion into the `semantic` field with the remote symmetric model doesn't work
### What is the bug?
For OpenSearch 3.3 I've had configured the index with the `semantic` field whose `model_id` pointed to a remote symmetric embedding model ("ext-embedding-ada-002")

However, after upgrading to OpenSearch 3.5 the ingestion doesn't work

### How can one reproduce the bug?
1. Create the index with the `semantic` field pointed to a remote symmetric embedding model ("ext-embedding-ada-002")
2. Ingest the data into the index

The 400 error is returned with the message "Remote models are only supported for asymmetric E5 text embedding"

### What is the expected behavior?
Data is ingested successfully

### What is your host/environment?
OpenSearch 3.5

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
It looks like a side-effect of https://github.com/opensearch-project/neural-search/pull/1605

### PR DESCRIPTION
**Pull request by bzhangam**
### Description
Remove the invalid validation to fix the issue where remote symmetric models are not supported.

Have manually set up remote dense and sparse model to verify it can work properly.

### Related Issues
Resolves #1765 

### Check List
- [x] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/neural-search/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/main/java/org/opensearch/neuralsearch/ml/NeuralSearchMLInputBuilder.java [hunk 1]
```diff
@@ -71,7 +67,7 @@ public static MLInput createTextEmbeddingInput(
         MLAlgoParams mlAlgoParams = createMLAlgoParams(isAsymmetric, inferenceRequest);
         ModelResultFilter modelResultFilter = new ModelResultFilter(false, true, targetResponseFilters, null);
         MLInputDataset inputDataset = new TextDocsInputDataSet(inputText, modelResultFilter);
-        return createLocalInput(FunctionName.TEXT_EMBEDDING, inputDataset, mlAlgoParams);
+        return new MLInput(FunctionName.TEXT_EMBEDDING, mlAlgoParams, inputDataset);
```
Comment (bzhangam) [inline src/main/java/org/opensearch/neuralsearch/ml/NeuralSearchMLInputBuilder.java:70]: I simply revert to the old way how we prepare the ML Input. It seems like the function name here doesn't matter since we use it for remote and local TEXT_EMBEDDING/SPARSE_ENCODING/SPARSE_TOKENIZE models.

File: CHANGELOG.md [hunk 2]
```diff
@@ -11,6 +11,7 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 
 ### Bug Fixes
 - [HYBRID]: Fix relevancy bugs in hybrid query collapse ([#1753](https://github.com/opensearch-project/neural-search/pull/1753))
+- Fix issue where remote symmetric models are not supported ([#1767](https://github.com/opensearch-project/neural-search/pull/1767))
```
Comment (vibrantvarun) [inline CHANGELOG.md]:
```suggestion
- [Neural] Fix issue where remote symmetric models are not supported ([#1767](https://github.com/opensearch-project/neural-search/pull/1767))
```

**Review by vibrantvarun — COMMENTED** [review]
Overall code looks good to me.
