### PR TITLE
[SEISMIC IT] fix IT failing

### LINKED ISSUE #1653: [BUG] NeuralSparseCacheOperationIT multi shard tests could fail if test env with non data nodes
### What is the bug?
NeuralSparseCacheOperationIT multi shard tests could fail if test env with setup like three data nodes and three master nodes as the tests expect memory usage to change after calling warmup and clearcache API. But with master nodes, they don't have seismic running on it and those API won't bring a change to memory usage.

### How can one reproduce the bug?
Run integration tests against remote clusters with 3 data nodes and 3 master nodes.

### What is the expected behavior?
integration should pass with different cluster configuration.

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

### PR DESCRIPTION
**Pull request by zirui-song-18**
### Description
This PR further fixed two failed IT cases when there are dedicated Master/Data nodes.

### Related Issues
Resolves #1653 

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/neural-search/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/test/java/org/opensearch/neuralsearch/sparse/NeuralSparseCacheOperationIT.java [hunk 1]
```diff
@@ -182,9 +182,13 @@ public void testWarmUpMultiShardReplicasCache() {
...
         assertTrue("Memory usage should increase after warm up", afterWarmUpSparseMemoryUsageSum > originalSparseMemoryUsageSum);
         assertEquals(originalSparseMemoryUsageStats.size(), afterWarmUpSparseMemoryUsageStats.size());
+        int nodesWithMemoryIncrease = 0;
         for (int i = 0; i < originalSparseMemoryUsageStats.size(); i++) {
-            assertTrue(afterWarmUpSparseMemoryUsageStats.get(i) > originalSparseMemoryUsageStats.get(i));
+            if (afterWarmUpSparseMemoryUsageStats.get(i) > originalSparseMemoryUsageStats.get(i)) {
+                nodesWithMemoryIncrease++;
+            }
         }
+        assertEquals("At least data nodes should have memory increase", nodesWithMemoryIncrease, getDataNodeCount());
```
Comment (yuye-aws) [inline src/test/java/org/opensearch/neuralsearch/sparse/NeuralSparseCacheOperationIT.java]: `At least data nodes should have memory increase` is guaranteed by `Memory usage should increase after warm up`. How about simply discarding the assertions

Comment (zirui-song-18) [reply src/test/java/org/opensearch/neuralsearch/sparse/NeuralSparseCacheOperationIT.java]: I think this assertion is to make sure every data nodes' memory work in our expected way. `Memory usage should increase after warm up` can only assert total memory.

Comment (yuye-aws) [reply src/test/java/org/opensearch/neuralsearch/sparse/NeuralSparseCacheOperationIT.java]: Sorry, I missed some context. After revisiting the recent PRs, I just have a simple question: How do you ensure every node has a memory increase?

Comment (zirui-song-18) [reply src/test/java/org/opensearch/neuralsearch/sparse/NeuralSparseCacheOperationIT.java]: Each data node will have memory change. That's why I modified here in this way. If we do not use `getDataNodeCount`, we might count Master node by mistake, then this will fail.

Comment (yuye-aws) [reply src/test/java/org/opensearch/neuralsearch/sparse/NeuralSparseCacheOperationIT.java]: No worries. Resolving this thread now.

Comment (bzhangam) [inline src/test/java/org/opensearch/neuralsearch/sparse/NeuralSparseCacheOperationIT.java]: How can we know the master node memory will not increase? Can we check the node role when we do this check?

Comment (zirui-song-18) [reply src/test/java/org/opensearch/neuralsearch/sparse/NeuralSparseCacheOperationIT.java]: This assertion here is to compare the number of data nodes and the number of nodes with memory increases. If they are equal, which means that only data nodes increase memory.

Comment (owaiskazi19) [reply src/test/java/org/opensearch/neuralsearch/sparse/NeuralSparseCacheOperationIT.java]: +1 to @bzhangam . We can also check for node.roles to be assure that only data nodes has increased memory

Comment (owaiskazi19) [inline src/test/java/org/opensearch/neuralsearch/sparse/NeuralSparseCacheOperationIT.java]:
```suggestion
        assertEquals("Only data nodes should have memory increase", nodesWithMemoryIncrease, getDataNodeCount());
```

File: src/test/java/org/opensearch/neuralsearch/sparse/NeuralSparseCacheOperationIT.java [hunk 2]
```diff
@@ -220,9 +224,13 @@ public void testClearMultiShardReplicasCache() {
...
         assertTrue("Memory usage should decrease after clear cache", afterClearCacheSparseMemoryUsageSum < originalSparseMemoryUsageSum);
         assertEquals(originalSparseMemoryUsageStats.size(), afterClearCacheSparseMemoryUsageStats.size());
+        int nodesWithMemoryDecrease = 0;
         for (int i = 0; i < originalSparseMemoryUsageStats.size(); i++) {
-            assertTrue(afterClearCacheSparseMemoryUsageStats.get(i) < originalSparseMemoryUsageStats.get(i));
+            if (afterClearCacheSparseMemoryUsageStats.get(i) < originalSparseMemoryUsageStats.get(i)) {
+                nodesWithMemoryDecrease++;
+            }
         }
+        assertEquals("At least data nodes should have memory decrease", nodesWithMemoryDecrease, getDataNodeCount());
```
Comment (owaiskazi19) [inline src/test/java/org/opensearch/neuralsearch/sparse/NeuralSparseCacheOperationIT.java]:
```suggestion
        assertEquals("Only data nodes should have memory decrease", nodesWithMemoryDecrease, getDataNodeCount());
```

Comment (owaiskazi19) [inline src/test/java/org/opensearch/neuralsearch/sparse/NeuralSparseCacheOperationIT.java]: Same as above we can check for node.roles here to verify

Comment (zirui-song-18) [reply src/test/java/org/opensearch/neuralsearch/sparse/NeuralSparseCacheOperationIT.java]: Ack. Now this assertion makes sure that only data nodes behave in the expected way. It should be fine.

File: src/test/java/org/opensearch/neuralsearch/sparse/NeuralSparseCacheOperationIT.java (hunk 1 above)
Comment (yuye-aws) [reply src/test/java/org/opensearch/neuralsearch/sparse/NeuralSparseCacheOperationIT.java]: This is a bit tricky here because the get memory stats API will not return node.roles. A workaround is "node_id". You can call cat nodes to obtain node_id for master nodes and data nodes.

Comment (zirui-song-18) [reply src/test/java/org/opensearch/neuralsearch/sparse/NeuralSparseCacheOperationIT.java]: I think latest version is a good choice. `getNodeCount()` directly return how many data nodes we have, where we only execute cache operations on those data nodes. Then in these two cases, we count how many nodes' memory increase/decrease, to assert whether that equals to the number of data nodes.

File: CHANGELOG.md [hunk 3]
```diff
@@ -14,7 +14,7 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 
 ### Bug Fixes
 - [SEISMIC]: Resolve a security risk of Sparse ANN - Move 'index.sparse' validation from REST to transport layer. ([#1630](https://github.com/opensearch-project/neural-search/pull/1630))
-- [SEISMIC IT]: Fix some failed IT cases ([#1649](https://github.com/opensearch-project/neural-search/pull/1649))
+- [SEISMIC IT]: Fix some failed IT cases ([#1649](https://github.com/opensearch-project/neural-search/pull/1649), [#1655](https://github.com/opensearch-project/neural-search/pull/1655))
```
Comment (owaiskazi19) [inline CHANGELOG.md]: We should clear the complete changelog since we have released the enhancement and bug fixes. And add this as a new entry for the next release

Comment (zirui-song-18) [reply CHANGELOG.md]: Thanks for that advice. Now I cleaned all those released items, just left this new change.

File: CHANGELOG.md [hunk 4]
```diff
@@ -8,17 +8,11 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
...
-- [Agentic Search] Extract agent summary based on models ([#1633](https://github.com/opensearch-project/neural-search/pull/1633))
 
 ### Bug Fixes
-- [SEISMIC]: Resolve a security risk of Sparse ANN - Move 'index.sparse' validation from REST to transport layer. ([#1630](https://github.com/opensearch-project/neural-search/pull/1630))
-- [SEISMIC IT]: Fix some failed IT cases ([#1649](https://github.com/opensearch-project/neural-search/pull/1649))
-- [Hybrid Search]: Fix for hybrid search collapse bug when there are no documents in a shard ([#1647](https://github.com/opensearch-project/neural-search/pull/1647))
+- [SEISMIC IT]: Fix some failed IT cases ([#1655](https://github.com/opensearch-project/neural-search/pull/1655))
 
 ### Infrastructure
-- Onboard to s3 snapshots ([#1618](https://github.com/opensearch-project/neural-search/pull/1618))
```
Comment (owaiskazi19) [inline CHANGELOG.md:21]: We don't have to remove this. This was added for the next release. Please add it back

Comment (zirui-song-18) [reply CHANGELOG.md:21]: Sure. Ack

**Comment by yuye-aws** [comment]
The CI failed due to issue https://github.com/opensearch-project/neural-search/issues/1660. Will merge this PR after the fix in https://github.com/opensearch-project/neural-search/pull/1657

**Comment by yuye-aws** [comment]
Hi @zirui-song-18 , I have just merged the BWC test PR. Can you rebase main to unblock the CI failure?
