### PR TITLE
Fix the HybridQueryDocIdStream to properly handle upTo value

### LINKED ISSUE #1344: [Flaky Test] HybridQueryTests.testWithRandomDocuments_whenMultipleTermSubQueriesWithMatch_thenReturnSuccessfully
https://github.com/opensearch-project/neural-search/pull/1336 introduced a flaky test org.opensearch.neuralsearch.query.HybridQueryTests.testWithRandomDocuments_whenMultipleTermSubQueriesWithMatch_thenReturnSuccessfully.

The test needs be investigated and fixed so it is not flaky.

### LINKED ISSUE #1407: [Flaky test]HybridQueryTests.testWithRandomDocuments_whenMultipleTermSubQueriesWithMatch_thenReturnSuccessfully
```
REPRODUCE WITH: gradlew ':test' --tests "org.opensearch.neuralsearch.query.HybridQueryTests.testWithRandomDocuments_whenMultipleTermSubQueriesWithMatch_thenReturnSuccessfully" -Dtests.seed=D6D9F52CDEBD6AE7 -Dtests.security.manager=false -Dtests.locale=pt-MO -Dtests.timezone=Australia/Darwin -Druntime.java=23
HybridQueryTests > testWithRandomDocuments_whenMultipleTermSubQueriesWithMatch_thenReturnSuccessfully FAILED
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([D6D9F52CDEBD6AE7:9F6ADF20695CBC7C]:0)
        at org.apache.lucene.tests.search.AssertingLeafCollector$AssertingDocIdStream.forEach(AssertingLeafCollector.java:141)
        at org.apache.lucene.tests.search.AssertingLeafCollector$AssertingDocIdStream.forEach(AssertingLeafCollector.java:132)
        at org.apache.lucene.tests.search.AssertingLeafCollector$AssertingDocIdStream.forEach(AssertingLeafCollector.java:132)
        at org.apache.lucene.search.LeafCollector.collect(LeafCollector.java:106)
        at org.apache.lucene.tests.search.AssertingLeafCollector.collect(AssertingLeafCollector.java:50)
        at org.apache.lucene.tests.search.AssertingLeafCollector.collect(AssertingLeafCollector.java:50)
        at org.apache.lucene.tests.search.AssertingLeafCollector.collect(AssertingLeafCollector.java:50)
        at org.opensearch.neuralsearch.query.HybridBulkScorer.scoreWindowIntoBitSetWithSubqueryScorers(HybridBulkScorer.java:150)
        at org.opensearch.neuralsearch.query.HybridBulkScorer.scoreWindow(HybridBulkScorer.java:98)
        at org.opensearch.neuralsearch.query.HybridBulkScorer.score(HybridBulkScorer.java:79)
        at org.apache.lucene.tests.search.AssertingBulkScorer.score(AssertingBulkScorer.java:79)
        at org.apache.lucene.search.IndexSearcher.searchLeaf(IndexSearcher.java:849)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:809)
        at org.apache.lucene.tests.search.AssertingIndexSearcher.search(AssertingIndexSearcher.java:77)
        at org.apache.lucene.search.IndexSearcher.lambda$search$1(IndexSearcher.java:779)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at org.apache.lucene.search.TaskExecutor$Task.run(TaskExecutor.java:173)
        at org.apache.lucene.search.TaskExecutor.invokeAll(TaskExecutor.java:111)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:783)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:750)
        at org.apache.lucene.search.IndexSearcher.searchAfter(IndexSearcher.java:596)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:619)
        at org.opensearch.neuralsearch.query.HybridQueryTests.testWithRandomDocuments_whenMultipleTermSubQueriesWithMatch_thenReturnSuccessfully(HybridQueryTests.java:176)
```

### PR DESCRIPTION
**Pull request by heemin32**
### Description
The HybridQueryDocIdStream class contained a bug in how it handled the upTo parameter. This issue led to a flaky test failure in HybridQueryTests.testWithRandomDocuments_whenMultipleTermSubQueriesWithMatch_thenReturnSuccessfully.

The failure occurred because the mayHaveRemaining method returned true even after all documents had been consumed from the hybridBulkScorer. As a result, OpenSearch Core attempted to call the forEach method again, which reconsumed documents from the beginning—triggering an assertion failure.

This PR addresses the issue by properly clearing document ID which was already consumed, ensuring that documents aren't reprocessed. It also fixes the mayHaveRemaining method to return false if there is no more document to process.

### Related Issues
Resolves #1344 

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [X] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/neural-search/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/main/java/org/opensearch/neuralsearch/query/HybridQueryDocIdStream.java [hunk 1]
```diff
@@ -19,66 +20,57 @@
...
+            throw new RuntimeException(e);
+        }
         return count[0];
     }
 
     @Override
-    public boolean mayHaveRemaining() {
-        return this.upTo + 1 < hybridBulkScorer.getMaxDoc();
-    }
+    public void forEach(int upTo, CheckedIntConsumer<IOException> consumer) throws IOException {
```
Comment (vibrantvarun) [inline src/main/java/org/opensearch/neuralsearch/query/HybridQueryDocIdStream.java:45]: Please add javadoc for public methods.

**Review by vibrantvarun — COMMENTED** [review]
Could you at high level write what is issue and how this fix address it?

File: src/main/java/org/opensearch/neuralsearch/query/HybridQueryDocIdStream.java [hunk 2]
```diff
@@ -52,33 +72,14 @@ public void forEach(int upTo, CheckedIntConsumer<IOException> consumer) throws I
...
-    public boolean mayHaveRemaining() {
-        return this.upTo + 1 < hybridBulkScorer.getMaxDoc();
-    }
-
-    public void setBase(int base) {
-        this.base = base;
-        this.upTo = base;
-    }
-}
+}
```
Comment (vibrantvarun) [inline src/main/java/org/opensearch/neuralsearch/query/HybridQueryDocIdStream.java]: Could you run  ./gradlew spotlessApply to remove this extra line

Comment (heemin32) [reply src/main/java/org/opensearch/neuralsearch/query/HybridQueryDocIdStream.java]: done

**Review by ryanbogan — APPROVED** [review]

File: src/main/java/org/opensearch/neuralsearch/query/HybridQueryDocIdStream.java [hunk 3]
```diff
@@ -19,17 +20,29 @@
...
+
+    @Override
+    public int count(int upTo) {
+        // Use a counter to track how many documents are processed
+        final int[] count = { 0 };
+        try {
+            forEach(upTo, docId -> count[0]++);
+        } catch (IOException e) {
+            // This should not happen as we're just counting, not doing any I/O
+            throw new RuntimeException(e);
```
Comment (martin-gaievski) [inline src/main/java/org/opensearch/neuralsearch/query/HybridQueryDocIdStream.java:40]: please add more information for potential troubleshooting, we need to log at error level and maybe some descriptive message for new runtime exception, e.g. "unexpected error while collecting ids for matching documents"

File: src/main/java/org/opensearch/neuralsearch/query/HybridQueryDocIdStream.java [hunk 4]
```diff
@@ -52,33 +72,14 @@ public void forEach(int upTo, CheckedIntConsumer<IOException> consumer) throws I
...
-                int doc = base | docIndexInWindow;
-                if (doc < upTo + base) {
-                    consumer.accept(doc);
-                    this.upTo++;
-                }
+                consumer.accept(docId);
                 // reset scores after processing of one doc, this is required because scorer object is re-used
                 hybridBulkScorer.getHybridSubQueryScorer().resetScores();
+                // clear bit from the actual bitset to indicate that it has been consumed
+                matchingBitSet.clear(docId);
```
Comment (martin-gaievski) [inline src/main/java/org/opensearch/neuralsearch/query/HybridQueryDocIdStream.java]: I'm not sure we need this, it can cause issues if we clearing the wrong bit

File: src/main/java/org/opensearch/neuralsearch/query/HybridQueryDocIdStream.java (hunk 3 above)
Comment (heemin32) [reply src/main/java/org/opensearch/neuralsearch/query/HybridQueryDocIdStream.java:40]: I believe all the required information will be logged by this exception anyway.

File: src/main/java/org/opensearch/neuralsearch/query/HybridQueryDocIdStream.java (hunk 4 above)
Comment (heemin32) [reply src/main/java/org/opensearch/neuralsearch/query/HybridQueryDocIdStream.java]: It is needed not to process the same document again. Anyway, I used wrong value here and also modified the bitset directly. I changed to use correct value and used cloned bitset.

**Review by martin-gaievski — APPROVED** [review]

File: src/main/java/org/opensearch/neuralsearch/query/HybridQueryDocIdStream.java [hunk 5]
```diff
@@ -52,33 +73,22 @@ public void forEach(int upTo, CheckedIntConsumer<IOException> consumer) throws I
...
-        return this.upTo + 1 < hybridBulkScorer.getMaxDoc();
-    }
-
-    public void setBase(int base) {
-        this.base = base;
-        this.upTo = base;
+    // This lazy loading is necessary because the matching bit isn't available at the time this class is constructed.
+    private FixedBitSet getLocalMatchingBitSet() {
+        if (localMatchingBitSet == null) {
+            localMatchingBitSet = hybridBulkScorer.getMatching().clone();
```
Comment (junqiu-lei) [inline src/main/java/org/opensearch/neuralsearch/query/HybridQueryDocIdStream.java:90]: Shall we verify behavior with documents trigger multiple windows? Current tests appear to use smaller datasets where this scenario wouldn't occur.

Comment (heemin32) [reply src/main/java/org/opensearch/neuralsearch/query/HybridQueryDocIdStream.java:90]: Not sure if such case should be implemented as integ test. Shouldn't it be captured by benchmark test or micro benchmark test instead?

Comment (heemin32) [reply src/main/java/org/opensearch/neuralsearch/query/HybridQueryDocIdStream.java:90]: Added a unit test instead.

**Review by junqiu-lei — APPROVED** [review]
