### PR TITLE
Change the behavior when embedding fields not present

### LINKED ISSUE #71: Not enough error information in error response when ingestion fails due to fields not present.
A customer got an error while trying out the neural plugin. Steps followed

Forum link: https://forum.opensearch.org/t/feedback-neural-search-plugin-experimental-release/11501/4

```
I got an error with the example in the documentation. Below is the code I tried. I tested the model and it is loading and working fine. However, ingesting the document fails giving the below error!

Environment: This was done on windows in development mode (one node as cluster_manager, data, ingest and ml)

Error:
{
“error” : {
“root_cause” : [
{
“type” : “illegal_argument_exception”,
“reason” : “empty docs”
}
],
“type” : “illegal_argument_exception”,
“reason” : “empty docs”
},
“status” : 400
}

My Code:
POST /_plugins/_ml/models/_upload
{
“name”: “all-MiniLM-L6-v2”,
“version”: “1.0.0”,
“description”: “test model”,
“model_format”: “TORCH_SCRIPT”,
“model_config”: {
“model_type”: “bert”,
“embedding_dimension”: 384,
“framework_type”: “sentence_transformers”
},
“url”: “[https://github.com/ylwu-amzn/ml-commons/blob/2.x_custom_m_helper/ml-algorithms/src/test/resources/org/opensearch/ml/engine/algorithms/text_embedding/all-MiniLM-L6-v2_torchscript_sentence-transformer.zip?raw=true 1](https://github.com/ylwu-amzn/ml-commons/blob/2.x_custom_m_helper/ml-algorithms/src/test/resources/org/opensearch/ml/engine/algorithms/text_embedding/all-MiniLM-L6-v2_torchscript_sentence-transformer.zip?raw=true)”
}

POST /_plugins/_ml/models/kI6NhoQB3oLQzIJTkldg/_load

POST /_plugins/_ml/models/kI6NhoQB3oLQzIJTkldg/_predict
{
“text_docs”:[ “today is sunny”]
}

PUT _ingest/pipeline/nlp-pipeline
{
“description”: “An example neural search pipeline”,
“processors” : [
{
“text_embedding”: {
“model_id”: “kI6NhoQB3oLQzIJTkldg”,
“field_map”: {
“text”: “text_knn”
}
}
}
]
}

PUT /my-nlp-index-1
{
“settings”: {
“index.knn”: true,

    "default_pipeline": "nlp-pipeline"
},
"mappings": {
    "properties": {
        "passage_embedding": {
            "type": "knn_vector",
            "dimension": 384,
            "method": {
                "name": "hnsw",
                "space_type": "l2",
                "engine": "nmslib",
                "parameters": {
                  "ef_construction": 128,
                  "m": 24
                }
            }
        },
        "passage_text": { 
            "type": "text"            
        }
    }
}
}

POST my-nlp-index-1/_doc
{
“passage_text”: “Hello world”
}
```

### PR DESCRIPTION
**Pull request by zane-neo**
Signed-off-by: Zan Niu <zaniu@amazon.com>

### Description
This PR is to optimize the error prompt message when inference list is empty, which is caused by user configuration error or expected fields empty. Previously the error message is too general for user to understand what's the root cause.

### Issues Resolved
#71 & #73 

### Check List
- [x] New functionality includes testing.
    - [x] All tests pass
- [x] New functionality has been documented.
    - [x] New functionality has javadoc added
- [x] Commits are signed as per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by jmazanec15** [comment]
@zane-neo add #71 to the description under issues resolved?

**Review by jmazanec15 — APPROVED** [review]

File: src/main/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessor.java [hunk 1]
```diff
@@ -100,7 +100,11 @@ public void execute(IngestDocument ingestDocument, BiConsumer<IngestDocument, Ex
         try {
             validateEmbeddingFieldsValue(ingestDocument);
             Map<String, Object> knnMap = buildMapWithKnnKeyAndOriginalValue(ingestDocument);
-            mlCommonsClientAccessor.inferenceSentences(this.modelId, createInferenceList(knnMap), ActionListener.wrap(vectors -> {
+            List<String> inferenceList = createInferenceList(knnMap);
```
Comment (navneet1v) [inline src/main/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessor.java:103]: Can we validate and see what will happen if knnMap is empty or null?

File: src/main/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessor.java [hunk 2]
```diff
@@ -100,7 +100,11 @@ public void execute(IngestDocument ingestDocument, BiConsumer<IngestDocument, Ex
...
+            if (inferenceList.size() == 0) {
+                throw new IllegalArgumentException("Unable to process embedding since no text found from corresponding source fields");
+            }
```
Comment (navneet1v) [inline src/main/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessor.java:106]: The inferenceList can be empty if the field which needs to inference is not present in the document. Please handle that use case in this PR.

Case when inference fields not present:
1. If for the document the field is genuinely not present.
2. In the update document use case the field to inference is not present as it doesn't need to be updated.

File: src/main/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessor.java (hunk 1 above)
Comment (zane-neo) [reply src/main/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessor.java:103]: The knnMap won't be null since it's manually created, but it could be empty if user doesn't configure anything in the pipeline field_map. This case the inference list will be empty.

File: src/main/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessor.java (hunk 2 above)
Comment (zane-neo) [reply src/main/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessor.java]: @jmazanec15 @navneet1v Yeah, This is something I want to discuss with you guys. The error information in fact is not a real issue. Since the cases Navneet mentioned above, we should succeed the ingestion without any exception raised. This way user will never see the exception so no need to handle the proper prompt. I've changed the code in this PR, please take a look.

Comment (navneet1v) [reply src/main/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessor.java]: @zane-neo 
I checked the code and it handles the case when user is updating the document, or even in the case when he is indexing the document for first time and he misses the fields. While this looks good. But the current code doesn't handle the case when user wants the ingestion request to fail because of lack of fields. I think we should think of that case too.

Comment (zane-neo) [reply src/main/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessor.java]: @navneet1v These two are conflict cases, if we prompt the user lacking of fields which means we don't allow user's insert/update(particular without embedding fields). If we allow user to ingest without embedding fields, we shouldn't raise error to user. I prefer allowing user's ingestion without embedding fields, since this is a valid case for user(Some documents do not have embedding fields).

Comment (navneet1v) [reply src/main/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessor.java]: @zane-neo The idea which I was thinking is let customer configure what they want to do in case the embedding fields are not present. One way to do this is by adding a parameter in the processor. But as of now I think we can go ahead with this change.
