### PR TITLE
Fix for collapse bug with knn query not deduplicating results

### LINKED ISSUE #1411: [BUG] [Hybrid Search with KNN] Collapse clause fails to deduplicate results
### What is the bug?
When performing a hybrid search that includes a KNN query, utilizes a search pipeline, and attempts to deduplicate results using the `collapse` clause, the `collapse` functionality fails to take effect. The search results are not deduplicated by the specified `field`, returning all matching documents instead of a single document per unique value of the collapsed field. The opensearch version is **3.1.0**, I see the feature **[RFC] Collapse in Hybrid Query** #1258 is done, but it seems it doesn't work with **KNN** search

### How can one reproduce the bug?
Follow these steps to reproduce the issue:

1.  **Create the `product_index`:**
    ````kibana
    PUT /product_index
    {
      "settings": {
        "number_of_shards": 1,
        "number_of_replicas": 1,
        "index": {
          "knn": true  
        }
      },
      "mappings": {
        "properties": {
          "product_name": {
            "type": "text"
          },
          "product_vector": {
            "type": "knn_vector",
            "dimension": 3 
          },
          "category": {
            "type": "keyword"
          }
        }
      }
    }
    ````

2.  **Index sample data:**
    ````kibana
    POST /product_index/_bulk
    {"index":{}}
    {"product_name":"Laptop Dell XPS 13","product_vector":[0.1,0.2,0.3],"category":"Electronics"}
    {"index":{}}
    {"product_name":"Smartphone Samsung Galaxy S21","product_vector":[0.4,0.5,0.6],"category":"Electronics"}
    {"index":{}}
    {"product_name":"Running Shoes Nike Air Zoom","product_vector":[0.7,0.8,0.9],"category":"Sports"}
    {"index":{}}
    {"product_name":"Coffee Maker Breville","product_vector":[0.2,0.3,0.4],"category":"Home Appliances"}
    {"index":{}}
    {"product_name":"Smart TV LG 55 Inch","product_vector":[0.5,0.6,0.7],"category":"Electronics"}
    ````

3.  **Create the `hybrid_pipeline`:**
    ````kibana
    PUT /_search/pipeline/hybrid_pipeline
    {
      "description": "Pipeline for hybrid search",
      "phase_results_processors": [
        {
          "normalization-processor": {
            "normalization": {
              "technique": "min_max"
            },
            "combination": {
              "technique": "arithmetic_mean",
              "parameters": {
                "weights": [0.5, 0.5]
              }
            }
          }
        }
      ]
    }
    ````

4.  **Execute the hybrid search query with `collapse`:**
    ````kibana
    POST /product_index/_search?search_pipeline=hybrid_pipeline
    {
      "query": {
        "hybrid": {
          "queries": [
            {
              "match": {
                "product_name": "laptop"
              }
            },
            {
              "knn": {
                "product_vector": {
                  "vector": [0.1, 0.2, 0.3],
                  "k": 10
                }
              }
            }
          ]
        }
      },
      "collapse": { "field": "category" }
    }
    ````

**Actual Result (Output from Step 4):**
````json
{
  "took": 236,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 5,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [
      {
        "_index": "product_index",
        "_id": "OPclq5cB3xjnwptML9ns",
        "_score": 1,
        "_source": {
          "product_name": "Laptop Dell XPS 13",
          "product_vector": [
            0.1,
            0.2,
            0.3
          ],
          "category": "Electronics"
        },
        "fields": {
          "category": [
            "Electronics"
          ]
        }
      },
      {
        "_index": "product_index",
        "_id": "O_clq5cB3xjnwptML9nt",
        "_score": 0.47195262,
        "_source": {
          "product_name": "Coffee Maker Breville",
          "product_vector": [
            0.2,
            0.3,
            0.4
          ],
          "category": "Home Appliances"
        },
        "fields": {
          "category": [
            "Home Appliances"
          ]
        }
      },
      {
        "_index": "product_index",
        "_id": "Ofclq5cB3xjnwptML9nt",
        "_score": 0.2952756,
        "_source": {
          "product_name": "Smartphone Samsung Galaxy S21",
          "product_vector": [
            0.4,
            0.5,
            0.6
          ],
          "category": "Electronics"
        },
        "fields": {
          "category": [
            "Electronics"
          ]
        }
      },
      {
        "_index": "product_index",
        "_id": "PPclq5cB3xjnwptML9nt",
        "_score": 0.18768771,
        "_source": {
          "product_name": "Smart TV LG 55 Inch",
          "product_vector": [
            0.5,
            0.6,
            0.7
          ],
          "category": "Electronics"
        },
        "fields": {
          "category": [
            "Electronics"
          ]
        }
      },
      {
        "_index": "product_index",
        "_id": "Ovclq5cB3xjnwptML9nt",
        "_score": 0.0005,
        "_source": {
          "product_name": "Running Shoes Nike Air Zoom",
          "product_vector": [
            0.7,
            0.8,
            0.9
          ],
          "category": "Sports"
        },
        "fields": {
          "category": [
            "Sports"
          ]
        }
      }
    ]
  }
}
````

The output shows 5 documents, with multiple documents from the "Electronics" category, indicating that `collapse` did not deduplicate.

### What is the expected behavior?
The expected behavior is that the `collapse` clause should deduplicate the search results based on the `category` field. This means only one document should be returned for each unique `category` found in the search results. For the provided sample data and query, the expected output should contain a maximum of 3 documents (one for "Electronics", one for "Home Appliances", and one for "Sports"), with the highest-scoring document chosen for each category.

### What is your host/environment?
*   **OpenSearch Version:** 3.1.0

### Do you have any screenshots?
Not applicable, as the issue is demonstrated through JSON output from the search API.

### Do you have any additional context?
This bug appears to be specific to the combination of `hybrid` queries (especially when including `knn`), the use of a `search_pipeline`, and the `collapse` feature. If the `knn` part is removed, the `collapse` feature might work as expected. 
Pls help me check the bug,  thank you very much.

### PR DESCRIPTION
**Pull request by ryanbogan**
### Description
Changes how the collapse context is retrieved in the hybrid collector factory.  This fixes a bug where sometimes the collapse context would incorrectly be read as null, which would 

### Related Issues
Resolves #1411

### Check List
- [X] New functionality includes testing.
- [X] New functionality has been documented.
- [] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [X] Commits are signed per the DCO using `--signoff`.
- [] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/neural-search/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/main/java/org/opensearch/neuralsearch/search/collector/HybridCollectorFactory.java [hunk 1]
```diff
@@ -32,9 +32,9 @@ public class HybridCollectorFactory {
      * @throws IllegalArgumentException If the search_after configuration is invalid.
      */
     public static Collector createCollector(HybridCollectorFactoryDTO hybridCollectorFactoryDTO) {
-        CollapseContext collapseContext = hybridCollectorFactoryDTO.getCollapseContext();
```
Comment (vibrantvarun) [inline src/main/java/org/opensearch/neuralsearch/search/collector/HybridCollectorFactory.java:35]: How come this can be null? If we set in HybridCollectorManager via searchContext already then

Comment (martin-gaievski) [reply src/main/java/org/opensearch/neuralsearch/search/collector/HybridCollectorFactory.java:35]: +1, is this a racing condition and we're buying ourselves more time?

Comment (owaiskazi19) [reply src/main/java/org/opensearch/neuralsearch/search/collector/HybridCollectorFactory.java:35]: +1. We are setting the collapseContext
https://github.com/opensearch-project/neural-search/blob/42b1c3e1192a257354bd0fcebd785e1c8c259e55/src/main/java/org/opensearch/neuralsearch/search/query/HybridCollectorManager.java#L651
which is reading it from searchContext. 
Can you trace to see how is it  coming as null in the DTO here?

Comment (owaiskazi19) [reply src/main/java/org/opensearch/neuralsearch/search/collector/HybridCollectorFactory.java:35]: Also, if this was the only place we needed collapseContext then we didn't need to add it the DTO in the first place since it negates the usage of DTO

Comment (ryanbogan) [reply src/main/java/org/opensearch/neuralsearch/search/collector/HybridCollectorFactory.java:35]: It was set to null via the constructor higher up, but it shouldn't have been.  I removed that section completely and just added it here.

Comment (ryanbogan) [reply src/main/java/org/opensearch/neuralsearch/search/collector/HybridCollectorFactory.java:35]:
```
filteringWeight,
                new TopDocsMerger(searchContext.sort()),
                searchContext.searchAfter(),
                searchContext,
                null
```

This got missed when it should have been passing in the collapse context

Comment (owaiskazi19) [reply src/main/java/org/opensearch/neuralsearch/search/collector/HybridCollectorFactory.java:35]: To minimize the changes in this PR, you can just pass ` searchContext.collapse()`
[here](https://github.com/opensearch-project/neural-search/pull/1413/files#diff-8cbc53de8660f6e4b4704ea4db1ce6d7c3325790a506b1c54dd376ce4511cf92L690)

Comment (ryanbogan) [reply src/main/java/org/opensearch/neuralsearch/search/collector/HybridCollectorFactory.java:35]: Yeah, that's true, but I figured that this is more efficient since we are only accessing it once instead of passing the object through multiple classes.

Comment (owaiskazi19) [reply src/main/java/org/opensearch/neuralsearch/search/collector/HybridCollectorFactory.java:35]: Agreed. Removing from DTO would make more sense here

**Review by owaiskazi19 — APPROVED** [review]
LGTM! Lessons learned: never pass a `null` :)

**Comment by vibrantvarun** [comment]
1. Add changelog

File: CHANGELOG.md [hunk 2]
```diff
@@ -10,6 +10,7 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 ### Enhancements
 
 ### Bug Fixes
+* Change where collapse context is read from in collector factory ([#1413](https://github.com/opensearch-project/neural-search/pull/1413))
```
Comment (vibrantvarun) [inline CHANGELOG.md]:
```suggestion
* Fix for collapse deduplication ([#1413](https://github.com/opensearch-project/neural-search/pull/1413))
```

Comment (vibrantvarun) [reply CHANGELOG.md]: Or maybe something better.

Comment (martin-gaievski) [reply CHANGELOG.md]: +1, let's make PR description closer to the user problem

Comment (ryanbogan) [reply CHANGELOG.md]: Added more details

**Comment by ryanbogan** [comment]
> gradle check is failing @ryanbogan

The test is flaky, unrelated to this change.  Can you restart the check?

**Review by martin-gaievski — APPROVED** [review]

**Review by vibrantvarun — APPROVED** [review]
